### PR TITLE
Add a shortcode to create an HTML sitemap

### PR DESCRIPTION
**Pull request by danielfdickinson**
Includes helper templates needed by the shortcode.

This (at the very least) needs documentation added, and likely you will want changes, if it is of interest. It is a copy of what I have in my fork.

### CODE REVIEW

**Comment by bwc69151** [comment]
Hi. I don't use this theme yet (but I intend to), but I tried your shortcode on my site and it only returns posts from one section that uses weight (not date) to group posts. The other sections that use date are omitted.

**Comment by frjo** [comment]
I do not think I have created a HTML sitemap in 15, or even 20 years.

What purpose do they fulfil nowadays?

**Comment by frjo** [comment]
The code is quite complicated and it feels like a nice feature. Maybe you should release it as a component? Then it can be added to any theme.

**Comment by danielfdickinson** [comment]
> The code is quite complicated and it feels like a nice feature. Maybe you should release it as a component? Then it can be added to any theme.

Sound reasonable. I'll do that. I'll close this PR and post a message on [the Hugo forum](https://discourse.gohugo.io) when I've created the component.

> I do not think I have created a HTML sitemap in 15, or even 20 years.
> What purpose do they fulfil nowadays?

This is a 'scratch my own itch' feature. An HTML sitemap allows me to get a sense of where things are on a site, as well as to find pages I would otherwise miss. Also, search is good if you know exactly what you are looking for and use the right keywords, but sometimes I am not being successful at coming up with the right query, but a sitemap gets me where I want to go.

**Comment by bwc69151** [comment]
Okay. I am not registered in the forum but I will check when you post. This current implementation was good though for presenting a TOC for a project I have that contains multiple chapters and over 400 articles.

**Pull request closed without merging**
